const CLOTHES=[['상의','👕'],['바지','👖'],['치마','👗'],['겉옷','🧥'],['신발','👟'],['모자','🧢'],['기타 의류','🧦']];
const CAREERS=['의류 상품 기획자(MD)','자산관리자','환경 지도자','패션 디자이너','섬유 소재 연구원','의류 수선 전문가','세탁·관리 전문가','윤리적 소비 컨설턴트','중고 의류 큐레이터','스타일리스트'];
const STEPS=[
 {title:'필요성',missions:[
  {title:'옷장 조사',q:['비슷한 옷을 이미 몇 벌 가지고 있나요?','가지고 있는 옷으로 해결할 수 없는 상황은 무엇인가요?','직접 확인한 옷장 상태를 어떤 근거로 기록했나요?']},
  {title:'생활 속 필요',q:['어느 계절과 활동에서 입으려고 하나요?','학교 규정이나 생활 일정에 맞나요?','필요한 시기는 언제이며 그 이유는 무엇인가요?']},
  {title:'필요 정도 선택',q:['지금 가진 옷으로 대신할 수 있나요?','앞으로 3개월 안에 입을 일이 있나요?','수선·빌리기·교환을 먼저 해볼 수 있나요?'],options:['꼭 필요함','있으면 유용함','지금은 필요하지 않음']}]},
 {title:'예산',missions:[
  {title:'가격 조사',q:['서로 다른 후보 상품 두 개의 가격은 얼마인가요?','판매처와 확인 날짜는 무엇인가요?','가격 차이가 나는 이유를 찾았나요?']},
  {title:'총비용과 한도',q:['배송비와 수선비를 포함한 총액은 얼마인가요?','내가 쓸 수 있는 한도는 얼마인가요?','다른 필요한 지출을 고려했나요?']},
  {title:'예산 범위 선택',q:['조사한 총액은 예산 안에 들어오나요?','가격이 달라지면 어떤 대안을 고를 건가요?','저축이나 다른 지출에 부담이 없나요?'],options:['예산 안에 듦','예산을 조금 넘음','예산을 많이 넘음']}]},
 {title:'활용도',missions:[
  {title:'착용 장면',q:['한 주에 어떤 날에 입을 수 있나요?','기존 옷 세 가지와 어떻게 조합하나요?','계절이나 학교생활 때문에 못 입는 때는 언제인가요?']},
  {title:'1회 착용 비용',q:['예상 구매 총액은 얼마인가요?','선택한 착용 횟수로 나누면 1회당 얼마인가요?','다른 후보 또는 기존 옷과 비교하면 어떤가요?']},
  {title:'월간 착용 횟수 선택',q:['선택한 달마다 한 달에 몇 번 입을 것 같나요?','입는 계절은 몇 개월인가요?','그 계산으로 1년에 몇 번이 되나요?'],options:['1~2회','3~5회','6~10회','11~20회','21회 이상']}]},
 {title:'소재',missions:[
  {title:'라벨 조사',q:['섬유 종류와 혼용률은 무엇인가요?','상품 페이지나 라벨의 출처는 어디인가요?','그 소재가 필요한 계절에 맞는 이유는 무엇인가요?']},
  {title:'착용감과 내구성',q:['보온성·통기성·신축성은 어떤가요?','봉제 상태와 원단 두께를 확인했나요?','자료나 사용 후기를 어떻게 확인했나요?']},
  {title:'소재 정보 확인 선택',q:['혼용률을 직접 확인했나요?','소재 특성을 신뢰할 자료가 있나요?','확인하지 못한 정보가 남아 있나요?'],options:['라벨과 출처 모두 확인','상품 설명만 확인','아직 확인하지 못함']}]},
 {title:'관리 가능성',missions:[
  {title:'세탁 표시',q:['물세탁·건조·다림질 표시는 무엇인가요?','직접 할 수 없는 관리 방법이 있나요?','세탁 정보를 어디서 확인했나요?']},
  {title:'오래 입는 방법',q:['얼마나 자주 세탁해야 하나요?','보관·얼룩 제거·수선은 어떻게 하나요?','관리 시간과 비용을 감당할 수 있나요?']},
  {title:'관리 난이도 선택',q:['집에 필요한 도구가 있나요?','내가 직접 관리할 수 있나요?','특별한 세탁 비용이 드나요?'],options:['혼자 관리 가능','도움이 있으면 가능','관리가 어려움']}]},
 {title:'종합 미션',missions:[
  {title:'최종 선택',q:['후보 두 개와 구매하지 않는 방법을 비교했나요?','필요성·예산·활용도·소재·관리를 모두 고려했나요?','최종적으로 무엇을 선택하고 왜 그렇게 결정했나요?']},
  {title:'실행 계획',q:['언제 어떤 판매처 또는 대안으로 실천하나요?','마지막으로 확인할 가격과 정보는 무엇인가요?','오래 입기 위한 관리 계획은 무엇인가요?']},
  {title:'현재 결론 선택',q:['지금 필요한 물건인가요?','예산과 관리가 가능한가요?','조사를 더 해야 할 부분이 있나요?'],options:['구매 또는 마련하기','기존 옷 활용·수선하기','결정 보류하고 더 조사하기']}]}
];
const KEY='closet-quest-v2';
const STATIC_MODE=window.CLOTHING_STATIC_MODE===true||window.location?.hostname?.endsWith('.github.io')===true;
const SHEET_WEB_APP_URL=String(window.CLOTHING_SHEET_WEB_APP_URL||'').trim();
const sheetConfigured=()=>/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec$/.test(SHEET_WEB_APP_URL);
const blank=()=>({submissionId:'',nickname:'',extra:{closet:'',prices:['','','',''],months:[],labels:[],scenario:'',finalChoice:''},grade:'',classroom:'',number:'',name:'',clothing:'',customClothing:'',steps:STEPS.map(()=>({answers:['','',''],done:false})),bonus:'',career:CAREERS[0],feedback:'',reflection:'',revision:'',view:'start'});
let state;try{state=Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||'{}'));if(!Array.isArray(state.steps)||state.steps.length!==6)state=blank();state.extra=Object.assign(blank().extra,state.extra||{});if(!Array.isArray(state.extra.prices)||state.extra.prices.length!==4)state.extra.prices=['','','',''];if(!Array.isArray(state.extra.months))state.extra.months=[];if(!Array.isArray(state.extra.labels))state.extra.labels=[];if(state.identity&&!state.grade&&!state.classroom&&!state.number&&!state.name){const match=state.identity.match(/^\s*(\d{1,2})\s*학년\s*(\d{1,2})\s*반\s*(\d{1,3})\s*번\s*(.+?)\s*$/);if(match){state.grade=match[1];state.classroom=match[2];state.number=match[3];state.name=match[4]}}}catch{state=blank()}
const app=document.getElementById('app');
const safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const identityText=()=>state.grade+'학년 '+state.classroom+'반 '+state.number+'번 '+state.name;
function garment(){
 const styles={
  '상의':['<path d="M31 20 18 26 8 43 24 52 29 43 29 83 Q50 89 71 83 L71 43 76 52 92 43 82 26 69 20 61 17 Q50 31 39 17Z" fill="#8ecce9" stroke="#235b69" stroke-width="3" stroke-linejoin="round"/><path d="M40 19 Q50 34 60 19" fill="none" stroke="#f9fcfb" stroke-width="4"/><path d="M32 72 Q50 78 68 72" fill="none" stroke="#5bacc9" stroke-width="2" stroke-dasharray="3 3"/>',50,51],
  '바지':['<path d="M23 15 Q50 11 77 15 L72 85 52 88 49 54 47 88 27 85Z" fill="#78a9df" stroke="#31567e" stroke-width="3" stroke-linejoin="round"/><path d="M24 27 Q50 30 76 27 M49 29 V50" fill="none" stroke="#d6e9fa" stroke-width="3"/><path d="M30 40 H41 M59 40 H70" stroke="#5d8fc5" stroke-width="2"/>',50,41],
  '치마':['<path d="M33 17 Q50 12 67 17 L77 38 86 83 Q50 91 14 83 L23 38Z" fill="#ef9dc0" stroke="#934d73" stroke-width="3" stroke-linejoin="round"/><path d="M33 18 Q50 25 67 18 M26 40 Q50 48 74 40" fill="none" stroke="#fff5fa" stroke-width="3"/><path d="M31 60 27 79 M69 60 73 79" stroke="#d878a5" stroke-width="2"/>',50,53],
  '겉옷':['<path d="M34 15 19 21 9 54 25 60 30 45 30 85 Q50 91 70 85 L70 45 75 60 91 54 81 21 66 15 58 20 50 33 42 20Z" fill="#f0b976" stroke="#875a39" stroke-width="3" stroke-linejoin="round"/><path d="M50 33 V85 M33 19 45 36 37 48 M67 19 55 36 63 48" fill="none" stroke="#fff0d4" stroke-width="3"/><circle cx="55" cy="48" r="2" fill="#fff"/><circle cx="55" cy="62" r="2" fill="#fff"/>',50,55],
  '신발':['<path d="M14 39 Q25 44 33 40 L46 57 Q62 60 78 64 Q87 67 89 76 L87 84 Q50 89 13 83 Q8 76 14 39Z" fill="#a9b9ef" stroke="#4e5a93" stroke-width="3" stroke-linejoin="round"/><path d="M13 75 Q47 80 88 76 M37 55 49 60 M42 50 54 55" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round"/><path d="M16 40 Q26 44 34 42" fill="none" stroke="#e0e7ff" stroke-width="4"/>',57,70],
  '모자':['<path d="M20 57 Q19 20 50 18 Q81 20 80 57Z" fill="#a8d886" stroke="#427646" stroke-width="3"/><path d="M16 56 Q50 50 84 56 Q90 60 88 67 Q50 73 12 67 Q10 61 16 56Z" fill="#77b667" stroke="#427646" stroke-width="3"/><path d="M50 20 V52" stroke="#d9f2bd" stroke-width="3"/>',50,43],
  '기타 의류':['<path d="M25 15 Q50 6 75 15 L78 77 Q50 91 22 77Z" fill="#bcb0e9" stroke="#625889" stroke-width="3" stroke-linejoin="round"/><path d="M30 25 Q50 32 70 25 M29 70 Q50 76 71 70" fill="none" stroke="#f5efff" stroke-width="3"/><path d="M25 37 17 45 25 52 M75 37 83 45 75 52" fill="none" stroke="#9588cc" stroke-width="3"/>',50,51]
 };
 const [body,x,y]=styles[state.clothing]||styles['상의'];
 return '<svg class="garment-art" viewBox="0 0 100 100" role="img" aria-label="'+safe(state.clothing||'옷')+' 일러스트" xmlns="http://www.w3.org/2000/svg"><ellipse cx="50" cy="93" rx="29" ry="4" fill="#d6e6d0"/>'+body+'<circle cx="'+(x-8)+'" cy="'+y+'" r="2.4" fill="#294d49"/><circle cx="'+(x+8)+'" cy="'+y+'" r="2.4" fill="#294d49"/><circle cx="'+(x-17)+'" cy="'+(y+5)+'" r="4" fill="#ee8d91" opacity=".65"/><circle cx="'+(x+17)+'" cy="'+(y+5)+'" r="4" fill="#ee8d91" opacity=".65"/><path d="M'+(x-4)+' '+(y+8)+' Q'+x+' '+(y+13)+' '+(x+4)+' '+(y+8)+'" fill="none" stroke="#294d49" stroke-width="2" stroke-linecap="round"/></svg>'
}
const garmentName=()=>state.clothing==='기타 의류'?(state.customClothing.trim()||'기타 의류'):state.clothing;
const questName=()=>state.nickname.trim()||garmentName();
const current=()=>{const i=state.steps.findIndex(s=>!s.done);return i<0?5:i};
const allDone=()=>state.steps.every(s=>s.done);
function button(label,act,style='primary',disabled=false){return '<button type="button" class="'+style+'" data-action="'+act+'"'+(disabled?' disabled':'')+'>'+label+'</button>'}
function title(heading,sub){return '<div class="hero"><h1>'+heading+'</h1><p>'+sub+'</p></div>'}
function actions(items){return '<div class="actions">'+items.join('')+'</div><p class="error" id="message" role="alert"></p>'}
function start(){return title('나의 옷장 <span class="lime">QUEST</span>','내가 마련하고 싶은 옷을 골라 탐험을 시작해요.')+
 '<div class="card"><h2>탐험 준비</h2><div class="student-grid"><div><label for="grade">학년</label><input id="grade" data-field="grade" inputmode="numeric" maxlength="2" placeholder="예: 2" value="'+safe(state.grade)+'"></div><div><label for="classroom">반</label><input id="classroom" data-field="classroom" inputmode="numeric" maxlength="2" placeholder="예: 3" value="'+safe(state.classroom)+'"></div><div><label for="number">번호</label><input id="number" data-field="number" inputmode="numeric" maxlength="3" placeholder="예: 12" value="'+safe(state.number)+'"></div><div><label for="student-name">이름</label><input id="student-name" data-field="name" maxlength="30" placeholder="예: 김하늘" value="'+safe(state.name)+'"></div></div><label for="clothing">마련하고 싶은 옷</label><select id="clothing" data-field="clothing"><option value="">옷을 선택하세요</option>'+CLOTHES.map(x=>'<option value="'+x[0]+'"'+(state.clothing===x[0]?' selected':'')+'>'+x[0]+'</option>').join('')+'</select>'+(state.clothing==='기타 의류'?'<label for="custom">어떤 옷인가요?</label><input id="custom" data-field="customClothing" maxlength="40" value="'+safe(state.customClothing)+'" placeholder="예: 교복 셔츠">':'')+'<label for="nickname">내 옷의 이름 짓기</label><input id="nickname" data-field="nickname" maxlength="40" placeholder="예: 비 오는 날 입을 겉옷" value="'+safe(state.nickname)+'">'+actions([button('탐험 시작 →','begin')])+'</div>'}
const positions=[[15,23],[50,23],[85,23],[85,77],[50,77],[15,77]];
function board(){return title('나의 옷장 <span class="lime">QUEST</span>',''+safe(identityText())+' · '+garment()+' '+safe(garmentName()))+
 '<div class="board"><svg class="route" viewBox="0 0 1000 470" preserveAspectRatio="none" aria-hidden="true"><path d="M150 108 H850 Q955 108 955 235 Q955 362 850 362 H150" fill="none" stroke="#b5d889" stroke-width="15" stroke-linecap="round" stroke-dasharray="24 16"/></svg><div class="spaces">'+STEPS.map((s,i)=>{let open=i<=current()||state.steps[i].done;return '<button class="space '+(state.steps[i].done?'done ':'')+(i===current()?'current':'')+'" style="left:'+positions[i][0]+'%;top:'+positions[i][1]+'%" data-action="step-'+i+'"'+(open?'':' disabled')+'><span class="stepno">'+(i===5?'FINAL':'STEP '+(i+1))+'</span><span class="piece">'+(i===current()?garment():(state.steps[i].done?'✓':'●'))+'</span><strong>'+s.title+'</strong><span class="mark">'+(state.steps[i].done?'미션 완료':i===current()?'내 옷의 현재 위치':'다음에 이동')+'</span></button>'}).join('')+'</div></div>'+evidenceCards()+actions([button('지속가능성 BONUS','bonus','secondary'),button('피드백 및 성찰 →','review','primary',!allDone()),button('처음 정보 수정','start','secondary')])}
function won(n){return Number(n||0).toLocaleString('ko-KR')+'원'}
function total(a,b){return Number(a||0)+Number(b||0)}
function estimatedWears(){const perMonth={'1~2회':2,'3~5회':4,'6~10회':8,'11~20회':15,'21회 이상':22}[state.steps[2].answers[2]];return perMonth?perMonth*state.extra.months.length:null}
function evidenceArt(i){
 const scenes=[
  '<rect x="31" y="13" width="58" height="66" rx="7" fill="#87c9a9" stroke="#285d4c" stroke-width="3"/><path d="M60 14v64 M36 28h19 M65 28h19" stroke="#f7fff8" stroke-width="3"/><circle cx="54" cy="53" r="2" fill="#285d4c"/><circle cx="66" cy="53" r="2" fill="#285d4c"/><path d="M48 31q12 15 24 0" fill="none" stroke="#f7fff8" stroke-width="2"/>',
  '<path d="M26 25 67 17 92 41 62 73 27 69Z" fill="#f6d784" stroke="#8b6b2f" stroke-width="3"/><circle cx="74" cy="38" r="5" fill="#fff8dc" stroke="#8b6b2f" stroke-width="2"/><path d="M43 50h23 M54 40v20" stroke="#8b6b2f" stroke-width="3" stroke-linecap="round"/><circle cx="87" cy="70" r="10" fill="#f4b75d" stroke="#8b6b2f" stroke-width="2"/>',
  '<rect x="25" y="18" width="70" height="61" rx="7" fill="#a7d6ef" stroke="#3c7292" stroke-width="3"/><path d="M26 36h68 M39 13v13 M80 13v13" stroke="#3c7292" stroke-width="4" stroke-linecap="round"/><path d="M39 51l6 6 10-13 M66 53h15 M39 68h15 M67 68h14" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>',
  '<path d="M23 26 70 17 91 66 42 78Z" fill="#d4b8ee" stroke="#72558e" stroke-width="3"/><path d="M36 24 58 72 M49 21 71 68 M63 19 82 62 M28 38 79 30 M34 51 85 43 M39 65 89 56" stroke="#f7ebff" stroke-width="2"/><path d="M83 16q19 15 3 31" fill="none" stroke="#72558e" stroke-width="3"/><circle cx="83" cy="15" r="3" fill="#72558e"/>',
  '<rect x="30" y="15" width="60" height="65" rx="9" fill="#9bdad0" stroke="#367469" stroke-width="3"/><path d="M31 29h58" stroke="#367469" stroke-width="3"/><circle cx="60" cy="54" r="20" fill="#e4f7f2" stroke="#367469" stroke-width="3"/><path d="M45 58q8-9 16 0t16 0" fill="none" stroke="#75bcb1" stroke-width="3"/><circle cx="42" cy="22" r="2" fill="#367469"/><circle cx="51" cy="22" r="2" fill="#367469"/>',
  '<path d="M58 20v58" stroke="#6a6c4d" stroke-width="6" stroke-linecap="round"/><path d="M57 29h35l-9 13H57Z" fill="#f0be76" stroke="#8f6639" stroke-width="3"/><path d="M57 51H22l9 13h26Z" fill="#92c988" stroke="#4d7650" stroke-width="3"/><path d="M46 79h27" stroke="#6a6c4d" stroke-width="4" stroke-linecap="round"/><path d="m81 13 3 5 6 1-4 5 1 6-6-3-5 3 1-6-4-5 6-1Z" fill="#f8d56e" stroke="#a4773c" stroke-width="2"/>'
 ];
 const labels=['옷장 그림','가격표와 동전 그림','달력 그림','원단 그림','세탁기 그림','선택의 갈림길 그림'];
 return '<svg class="evidence-art" viewBox="0 0 120 90" role="img" aria-label="'+labels[i]+'" xmlns="http://www.w3.org/2000/svg"><circle cx="60" cy="45" r="42" fill="#ffffff" opacity=".62"/>'+scenes[i]+'</svg>'
}
function evidenceCards(){const texts=['필요성의 단서','예산의 단서','활용도의 단서','소재의 단서','관리의 단서','최종 선택의 단서'];return '<section class="evidence"><h2>내가 모은 근거 카드</h2><div class="evidence-list">'+STEPS.map((step,i)=>'<article class="evidence-card '+(state.steps[i].done?'collected':'')+'"><div class="evidence-picture">'+evidenceArt(i)+'</div><div class="evidence-caption"><strong>'+texts[i]+'</strong><span class="evidence-status">'+(state.steps[i].done?'찾았어요 ✦':'아직 탐험 중')+'</span><small>'+(state.steps[i].done?safe(state.steps[i].answers[2]):'미션을 마치면 열려요')+'</small></div></article>').join('')+'</div></section>'}
function mini(i){
 const ex=state.extra;
 if(i===0)return '<div class="mini"><h2>🔎 옷장 탐정 카드</h2><p>옷장을 실제로 살펴보고 비슷한 옷이 몇 벌인지 고르세요.</p><div class="choice-row">'+['0벌','1~2벌','3벌 이상'].map(v=>'<button type="button" class="choice '+(ex.closet===v?'selected':'')+'" data-action="closet-'+v+'">'+v+'</button>').join('')+'</div></div>';
 if(i===1)return '<div class="mini"><h2>🏷️ 가격표 뒤집기</h2><p>후보 2개의 옷값과 배송비를 적으면 총액이 바로 나타나요.</p><div class="price-grid">'+['후보 A 옷값','후보 A 배송비','후보 B 옷값','후보 B 배송비'].map((label,j)=>'<label>'+label+' (원)<input type="number" min="0" max="100000000" step="1" inputmode="numeric" data-price="'+j+'" value="'+safe(ex.prices[j])+'" placeholder="0"></label>').join('')+'</div><div class="result" id="budget-result">'+budgetResult()+'</div></div>';
 if(i===2)return '<div class="mini"><h2>🗓️ 착용 달력</h2><p>이 옷을 입을 달을 눌러 보세요. 선택한 달과 착용 횟수로 1년 예상 횟수를 계산해요.</p><div class="month-grid">'+Array.from({length:12},(_,n)=>{let v=n+1;return '<button type="button" class="choice '+(ex.months.includes(v)?'selected':'')+'" data-action="month-'+v+'" aria-pressed="'+ex.months.includes(v)+'">'+v+'월</button>'}).join('')+'</div><div class="result" id="wear-result">'+wearResult()+'</div></div>';
 if(i===3)return '<div class="mini"><h2>🧵 라벨 찾기 미션</h2><p>상품 페이지나 실제 라벨에서 찾은 항목을 표시하세요.</p><div class="check-list">'+['섬유 종류','혼용률','세탁 표시'].map(v=>'<label><input type="checkbox" data-label="'+v+'" '+(ex.labels.includes(v)?'checked':'')+'> '+v+'</label>').join('')+'</div><p class="small">확인하지 못한 항목은 아래 조사 답변에 그 이유를 적어도 좋아요.</p></div>';
 if(i===4)return '<div class="mini"><h2>🫧 관리 상황 카드</h2><p>한 상황을 골라 아래 관리 방법 조사에 적용해 보세요.</p><select data-extra="scenario" aria-label="관리 상황 선택"><option value="">상황 고르기</option>'+['비 오는 날 옷이 젖었어요','옷에 얼룩이 생겼어요','옷의 단추가 떨어졌어요'].map(v=>'<option '+(ex.scenario===v?'selected':'')+'>'+v+'</option>').join('')+'</select></div>';
 return '<div class="mini"><h2>🛤️ 선택의 갈림길</h2><p>지금 나에게 가장 알맞은 길은 무엇인가요?</p><div class="choice-row">'+['새 옷 마련','기존 옷 활용·수선','더 조사하기'].map(v=>'<button type="button" class="choice '+(ex.finalChoice===v?'selected':'')+'" data-action="final-'+v+'">'+v+'</button>').join('')+'</div></div>';
}
function budgetResult(){const p=state.extra.prices;return '후보 A 총액 '+(p[0]!==''?won(total(p[0],p[1])):'미입력')+'　|　후보 B 총액 '+(p[2]!==''?won(total(p[2],p[3])):'미입력')}
function wearResult(){const n=estimatedWears();return n===null?'아래에서 월간 착용 횟수를 선택하고 달력에서 입을 달을 눌러 주세요.':'선택한 '+state.extra.months.length+'개월 × 월간 대표 횟수 = 연간 약 '+n+'회 (대략적인 추정)'+(state.extra.prices[0]!==''&&n>0?' · 후보 A는 1회당 약 '+won(Math.round(total(state.extra.prices[0],state.extra.prices[1])/n)):'')}
function mission(m,i,j){let a=state.steps[i].answers[j];return '<div class="mission"><h3><span class="number">'+(j+1)+'</span>'+m.title+'</h3><ol class="questions">'+m.q.map(q=>'<li>'+safe(q)+'</li>').join('')+'</ol>'+(m.options?'<label for="answer-'+j+'">조사 결과에 가까운 답을 선택하세요</label><select id="answer-'+j+'" data-answer="'+i+'-'+j+'"><option value="">선택하세요</option>'+m.options.map(o=>'<option'+(a===o?' selected':'')+'>'+safe(o)+'</option>').join('')+'</select>':'<textarea aria-label="'+safe(m.title)+' 답변" id="answer-'+j+'" data-answer="'+i+'-'+j+'" maxlength="1500" placeholder="조사 결과와 출처·확인 날짜를 함께 적어 주세요.">'+safe(a)+'</textarea>')+'</div>'}
function step(i){let s=STEPS[i];return title((i===5?'FINAL':'STEP '+(i+1))+' <span class="lime">'+s.title+'</span>',garment()+' '+safe(garmentName())+'의 정보를 직접 조사해 보세요.')+mini(i)+s.missions.map((m,j)=>mission(m,i,j)).join('')+actions([button('미션 완료하고 이동 →','finish-'+i),button('탐험판 이동','board','secondary')])}
function bonus(){return title('지속가능성 <span class="lime">BONUS</span>','선택 사항인 학습 확장 활동이에요.')+'<div class="mission"><h3>옷의 다음 여정</h3><ol class="questions"><li>이 옷은 어떻게 생산되고 이동했을까요?</li><li>더 오래 입기 위해 어떤 수선·관리 방법을 쓸 수 있을까요?</li><li>입지 않게 되면 어떻게 나누거나 순환시킬 수 있을까요?</li></ol><textarea data-field="bonus" maxlength="2000" placeholder="조사 자료와 실천할 행동을 적어 보세요.">'+safe(state.bonus)+'</textarea></div>'+actions([button('탐험판 이동','board','secondary')])}
function review(){if(!allDone())return board();return title('피드백 <span class="lime">및 성찰</span>','의생활 분야 직업인의 관점으로 나의 의복 마련 계획을 점검해 보세요')+
 '<div class="card"><label for="career">직업인 선택</label><select id="career" data-field="career">'+CAREERS.map(c=>'<option'+(state.career===c?' selected':'')+'>'+safe(c)+'</option>').join('')+'</select><p class="small">'+(STATIC_MODE?'이 GitHub Pages 버전은 AI가 아닌 자동 점검을 제공합니다. 자동 점검은 외부로 전송하지 않으며, 스프레드시트 제출을 누를 때 학생 정보와 답변이 Google로 전송됩니다.':'실제 AI 피드백을 요청합니다. 이름표는 전송하지 않고 미션 답변과 미니 활동 결과만 전송합니다.')+'</p>'+actions([button(STATIC_MODE?'자동 점검 받기':'AI 피드백 받기','feedback')])+(state.feedback?'<h3>'+safe(state.career)+'의 '+(STATIC_MODE?'자동 점검':'AI 피드백')+'</h3><div class="feedback">'+safe(state.feedback)+'</div>':'')+'</div>'+
 (state.feedback?'<div class="mission"><h3>나의 선택 성찰</h3><ol class="questions"><li>피드백에서 동의하는 점은 무엇인가요?</li><li>다시 확인할 가격·소재·관리 정보는 무엇인가요?</li><li>내 의복 선택 기준은 어떻게 달라졌나요?</li></ol><textarea data-field="reflection" maxlength="2500">'+safe(state.reflection)+'</textarea></div><div class="mission"><h3>수정·보완한 최종 계획</h3><ol class="questions"><li>옷을 마련할지, 기존 옷을 활용할지 어떻게 결정했나요?</li><li>예산과 착용·관리 계획을 어떻게 바꾸었나요?</li><li>언제 어떤 행동을 할 예정인가요?</li></ol><textarea data-field="revision" maxlength="3000">'+safe(state.revision)+'</textarea></div>'+actions([button('PDF로 저장','pdf','primary',!state.reflection.trim()||!state.revision.trim()),sheetForm(!state.reflection.trim()||!state.revision.trim()||!sheetConfigured()),button('탐험판 이동','board','secondary')]):actions([button('탐험판 이동','board','secondary')]))}
function sheetForm(disabled){return '<form class="sheet-form" action="'+safe(SHEET_WEB_APP_URL)+'" method="POST" target="_blank" data-sheet-form><input type="hidden" name="payload"><button type="submit" class="secondary"'+(disabled?' disabled':'')+'>스프레드시트에 제출</button></form>'+(sheetConfigured()?'<p class="small">새 창에서 제출 완료 메시지를 확인하세요. 수정 후 다시 제출하면 같은 행이 갱신됩니다.</p>':'<p class="small">스프레드시트 제출은 선생님이 연결한 뒤 사용할 수 있습니다.</p>')}
function submissionPayload(){return {version:1,submissionId:state.submissionId,student:{grade:state.grade,classroom:state.classroom,number:state.number,name:state.name},clothing:garmentName(),nickname:questName(),steps:STEPS.map((step,i)=>({name:step.title,answers:[...state.steps[i].answers]})),extra:state.extra,bonus:state.bonus,career:state.career,feedback:state.feedback,reflection:state.reflection,revision:state.revision}}
app.addEventListener('submit',e=>{if(!e.target.matches('[data-sheet-form]'))return;if(!sheetConfigured()||!allDone()||!state.feedback||!state.reflection.trim()||!state.revision.trim()){e.preventDefault();return}if(!state.submissionId)state.submissionId=window.crypto.randomUUID();save();e.target.querySelector('[name="payload"]').value=JSON.stringify(submissionPayload())});
function guidedFeedback(){const focus={'의류 상품 기획자(MD)':'후보 상품의 가격·소재·용도를 나란히 비교하세요.','자산관리자':'총비용과 1회 착용 비용을 예산과 비교하세요.','환경 지도자':'새 옷 이외에 수선·교환·중고 선택을 비교하세요.','패션 디자이너':'기존 옷과 어울리는 조합을 시험하세요.','섬유 소재 연구원':'섬유 혼용률의 출처와 계절 적합성을 확인하세요.','의류 수선 전문가':'수선으로 필요한 기능을 채울 수 있는지 확인하세요.','세탁·관리 전문가':'세탁 라벨과 실제 관리 시간을 확인하세요.','윤리적 소비 컨설턴트':'인증·생산 정보의 근거를 확인하세요.','중고 의류 큐레이터':'중고 옷의 상태와 실측을 확인하세요.','스타일리스트':'착용 장면과 기존 옷의 조합을 확인하세요.'};return '자동 점검 (AI 작성 아님)\n\n잘한 점: '+garmentName()+'에 대해 여섯 단계를 모두 조사했습니다.\n\n더 살펴볼 점: '+focus[state.career]+'\n출처와 확인 날짜가 빠진 답변은 보완해 보세요.\n\n수정 제안: 예산·예상 착용 횟수·관리 방법을 다시 비교하고, 구매하지 않는 대안까지 포함해 최종 계획을 적어 보세요.'}
function extraSummary(i){const e=state.extra;if(i===0)return '비슷한 옷 '+(e.closet||'미선택');if(i===1)return budgetResult();if(i===2)return (e.months.length?e.months.join(', ')+'월 / ':'')+wearResult();if(i===3)return '확인한 라벨: '+(e.labels.join(', ')||'없음');if(i===4)return e.scenario||'상황 미선택';return e.finalChoice||'선택 보류'}
function report(){return '<article class="report"><h1>나의 옷장 QUEST · 활동 결과</h1><p><strong>학년:</strong> '+safe(state.grade)+'　<strong>반:</strong> '+safe(state.classroom)+'　<strong>번호:</strong> '+safe(state.number)+'　<strong>이름:</strong> '+safe(state.name)+'</p><p><strong>마련할 옷:</strong> '+safe(garmentName())+'　<strong>내 옷의 이름:</strong> '+safe(questName())+'</p>'+evidenceCards()+STEPS.map((s,i)=>'<section><h2>'+(i===5?'FINAL':'STEP '+(i+1))+' '+s.title+'</h2><p><strong>미니 활동:</strong> '+safe(extraSummary(i))+'</p>'+s.missions.map((m,j)=>'<p><strong>'+m.title+'</strong><br>'+safe(state.steps[i].answers[j])+'</p>').join('')+'</section>').join('')+'<section><h2>지속가능성 BONUS</h2><p>'+safe(state.bonus)+'</p></section><section><h2>피드백 및 성찰</h2><p><strong>'+safe(state.career)+'</strong></p><p>'+safe(state.feedback)+'</p><h3>나의 성찰</h3><p>'+safe(state.reflection)+'</p><h3>수정·보완 계획</h3><p>'+safe(state.revision)+'</p></section></article>'}
function render(){let view=state.view;app.innerHTML='<div class="screen">'+(view==='start'?start():view==='board'?board():view==='bonus'?bonus():view==='review'?review():view.startsWith('step-')?step(Number(view.slice(5))):start())+'</div>'+report()}
app.addEventListener('input',e=>{let f=e.target.dataset.field;if(f){if(['grade','classroom','number','name'].includes(f)&&state[f]!==e.target.value)state.submissionId='';state[f]=e.target.value;save()}let a=e.target.dataset.answer;if(a){let [i,j]=a.split('-').map(Number);state.steps[i].answers[j]=e.target.value;state.steps[i].done=false;state.feedback='';state.reflection='';state.revision='';save()}if(f==='scenario'){state.extra.scenario=e.target.value;save()}let price=e.target.dataset.price;if(price!==undefined){state.extra.prices[Number(price)]=e.target.value;save();let out=app.querySelector('#budget-result');if(out)out.textContent=budgetResult()}if(f==='reflection'||f==='revision'){let b=app.querySelector('[data-action="pdf"]');if(b)b.disabled=!state.reflection.trim()||!state.revision.trim()}});
app.addEventListener('change',e=>{let f=e.target.dataset.field;if(f){state[f]=e.target.value;if(f==='career'){state.feedback='';state.reflection='';state.revision=''}save();if(f==='clothing'||f==='career')render()}let a=e.target.dataset.answer;if(a){let [i,j]=a.split('-').map(Number);state.steps[i].answers[j]=e.target.value;state.steps[i].done=false;state.feedback='';save();if(i===2){let out=app.querySelector('#wear-result');if(out)out.textContent=wearResult()}if(i===5&&j===2){const mapped={'구매 또는 마련하기':'새 옷 마련','기존 옷 활용·수선하기':'기존 옷 활용·수선','결정 보류하고 더 조사하기':'더 조사하기'};state.extra.finalChoice=mapped[e.target.value]||'';save();app.querySelectorAll('.choice-row .choice').forEach(b=>b.classList.toggle('selected',b.textContent===state.extra.finalChoice))}}let label=e.target.dataset.label;if(label){state.extra.labels=e.target.checked?[...new Set([...state.extra.labels,label])]:state.extra.labels.filter(x=>x!==label);save()}let extra=e.target.dataset.extra;if(extra){state.extra[extra]=e.target.value;save()}});
app.addEventListener('click',async e=>{let a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;let m=app.querySelector('#message');
 if(a.startsWith('closet-')){state.extra.closet=a.slice(7);save();render();return}
 else if(a.startsWith('month-')){let n=Number(a.slice(6));state.extra.months=state.extra.months.includes(n)?state.extra.months.filter(x=>x!==n):[...state.extra.months,n].sort((x,y)=>x-y);save();render();return}
 else if(a.startsWith('final-')){state.extra.finalChoice=a.slice(6);const mapped={'새 옷 마련':'구매 또는 마련하기','기존 옷 활용·수선':'기존 옷 활용·수선하기','더 조사하기':'결정 보류하고 더 조사하기'};state.steps[5].answers[2]=mapped[state.extra.finalChoice]||'';state.steps[5].done=false;state.feedback='';save();render();return}
 else if(a==='begin'){if(!/^\d{1,2}$/.test(state.grade)||!/^\d{1,2}$/.test(state.classroom)||!/^\d{1,3}$/.test(state.number)||!state.name.trim()||!state.clothing||(state.clothing==='기타 의류'&&!state.customClothing.trim())){m.textContent='학년·반·번호·이름을 각각 입력하고 옷을 선택해 주세요.';return}state.view='board'}
 else if(a.startsWith('finish-')){let i=Number(a.slice(7)),v=state.steps[i].answers;if(!v[0].trim()||v[0].trim().length<10||!v[1].trim()||v[1].trim().length<10||!v[2]){m.textContent='두 조사 내용을 각각 10자 이상 쓰고 선택형 답도 골라 주세요.';return}state.steps[i].done=true;state.view='board'}
 else if(a==='feedback'){let b=e.target;b.disabled=true;m.textContent='피드백을 준비하고 있습니다…';try{if(STATIC_MODE){state.feedback=guidedFeedback()}else{let r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({career:state.career,clothing:garmentName(),extra:state.extra,steps:state.steps})});const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw Error('AI 서버에 연결할 수 없습니다. 운영자에게 서버 설정을 확인해 달라고 알려 주세요.');let d=await r.json();if(!r.ok)throw Error(d.error||'피드백 요청 실패');state.feedback=d.feedback}state.reflection='';state.revision='';save();render()}catch(err){m.textContent=err.message;b.disabled=false}return}
 else if(a==='pdf'){if(allDone()&&state.feedback&&state.reflection.trim()&&state.revision.trim())window.print();return}
 else state.view=a;save();render();window.scrollTo(0,0)
});
render();
